plugins {
    id 'com.android.application'
}

android {
    namespace 'com.nhtool.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.nhtool.stable'
        minSdk 21
        targetSdk 35
        versionCode 205
        versionName '2.0.5'
    }

    buildTypes {
        debug {
            minifyEnabled false
            shrinkResources false
        }
        release {
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
